import { Template } from 'e2b'

export const template = Template()
  .fromImage('node:22-slim')
  .setUser('root')
  .setWorkdir('/')
  .runCmd('apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*')
  .copy('compile_page.sh', '/compile_page.sh')
  .runCmd('chmod +x /compile_page.sh')
  .setWorkdir('/home/user/nextjs-app')
  .runCmd('npx --yes create-next-app@16.2.1 . --yes --no-src-dir')
  .runCmd('npx --yes shadcn@4.1.1 init --defaults --force')
  .runCmd('npx --yes shadcn@4.1.1 add --all --yes')
  .runCmd('npm install tw-animate-css')
  .runCmd('mkdir -p app/api/health')
  .copy('health-route.ts', '/home/user/nextjs-app/app/api/health/route.ts')
  .copy('global-error.tsx', '/home/user/nextjs-app/app/global-error.tsx')
  .copy('console-capture.js', '/home/user/nextjs-app/public/console-capture.js')
  .runCmd('npm install')
  .runCmd('cp -rT /home/user/nextjs-app /home/user && rm -rf /home/user/nextjs-app')
  .setWorkdir('/home/user')
  .setUser('user')
  .setStartCmd('sudo /compile_page.sh', 'sleep 20')